version: '3.7'

services:
  web:
    env_file: ${WEB_ENV_PATH}
    restart: always
    container_name: blog-webapp
    image: armandoanaya_blog:prod
    build:
      context: ${WEB_CONTEXT_PATH}
      dockerfile: docker/production/Dockerfile
    expose:
      - 8000
    depends_on:
      - db

  db:
    env_file: ${DB_ENV_PATH}
    restart: always
    image: postgres:12.3-alpine
    container_name: blog-db
    volumes:
      - postgresdb_data:/var/lib/postgresql/data/

  nginx:
    restart: always
    image: nginx:1.19.0-alpine
    container_name: blog-nginx
    ports:
      - target: 80
        published: ${NGINX_PUBLIC_PORT}
        protocol: tcp
        mode: host
    depends_on:
      - web
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d

volumes:
  postgresdb_data:

# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
