version: '3.7'

services:
  web:
    env_file: ${WEB_ENV_PATH}
    restart: always
    container_name: blog-webapp
    image: armandoanaya_blog:prod
    build:
      context: ${WEB_CONTEXT_PATH}
      dockerfile: docker/production/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    env_file: ${DB_ENV_PATH}
    restart: always
    image: postgres:12.3-alpine
    container_name: blog-db
    volumes:
      - postgresdb_data:/var/lib/postgresql/data/

volumes:
  postgresdb_data:
