version: '3.7'

services:
  web:
    env_file: ${WEB_ENV_PATH}
    restart: always
    container_name: blog-webapp
    image: armandoanaya_blog:prod
    build:
      context: ${WEB_CONTEXT_PATH}
      dockerfile: docker/production/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    env_file: ${DB_ENV_PATH}
    restart: always
    image: postgres:12.3-alpine
    container_name: blog-db
    expose:
      - 5432
    volumes:
      - postgresdb_data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:4-alpine
    container_name: blog-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  postgresdb_data:
  redis_data:
