version: "3"

services:
  web:
    container_name: armando-blog
    image: armandoanaya_blog:latest
    build:
      context: ../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../:/code:cached
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./development/development.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.3-alpine
    container_name: blog-db
    expose:
      - 5432
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=armandoanaya_blog

  redis:
    image: redis:4-alpine
    container_name: blog-redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  postgresdb_data:
  redis_data:
